events:
    pattern:  /
    defaults: { _controller: "PayutcOnyxBundle:Event:index" }

events_show:
    pattern:  /{id}/show
    defaults: { _controller: "PayutcOnyxBundle:Event:show" }

events_new:
    pattern:  /new
    defaults: { _controller: "PayutcOnyxBundle:Event:new" }

events_create:
    pattern:  /create
    defaults: { _controller: "PayutcOnyxBundle:Event:create" }
    requirements: { _method: post }

events_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PayutcOnyxBundle:Event:edit" }

events_update:
    pattern:  /{id}/update
    defaults: { _controller: "PayutcOnyxBundle:Event:update" }
    requirements: { _method: post|put }

events_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PayutcOnyxBundle:Event:delete" }
    requirements: { _method: post|delete }
