tickets:
    pattern:  /
    defaults: { _controller: "PayutcOnyxBundle:Ticket:index" }

tickets_show:
    pattern:  /{id}/show
    defaults: { _controller: "PayutcOnyxBundle:Ticket:show" }

tickets_new:
    pattern:  /new
    defaults: { _controller: "PayutcOnyxBundle:Ticket:new" }

tickets_create:
    pattern:  /create
    defaults: { _controller: "PayutcOnyxBundle:Ticket:create" }
    requirements: { _method: post }

tickets_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PayutcOnyxBundle:Ticket:edit" }

tickets_update:
    pattern:  /{id}/update
    defaults: { _controller: "PayutcOnyxBundle:Ticket:update" }
    requirements: { _method: post|put }

tickets_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PayutcOnyxBundle:Ticket:delete" }
    requirements: { _method: post|delete }
