parameters:
    cas_user_provider.class: Payutc\OnyxBundle\CAS\CASUserProvider

services:
    cas_user_provider:
        class: "%cas_user_provider.class%"
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            encoderFactory: "@security.encoder_factory"
