parameters:
#    payutc_admin.example.class: Payutc\AdminBundle\Example

services:
#    payutc_admin.example:
#        class: %payutc_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
